
version: '3.7'

services:

  ragger-client:
    build:
      context: client
    user: nobody
    image: cyberdojo/ragger-client
    init: true
    container_name: test-ragger-client
    ports: [ "5538:5538" ]
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "./test:/test/:ro" ]
    depends_on: [ ragger ]

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  ragger:
    build:
      context: app
      args: [ COMMIT_SHA, CYBER_DOJO_RAGGER_PORT ]
    user: nobody
    image: ${CYBER_DOJO_RAGGER_IMAGE}
    init: true
    container_name: test-ragger-server
    environment: [ NO_PROMETHEUS ]
    export: ${CYBER_DOJO_RAGGER_PORT}
    ports: [ "${CYBER_DOJO_RAGGER_PORT}:${CYBER_DOJO_RAGGER_PORT}" ]
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "./test:/test/:ro" ]
    depends_on: [ runner ]

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  runner:
    user: root
    image: ${CYBER_DOJO_RUNNER_IMAGE}:${CYBER_DOJO_RUNNER_TAG}
    init: true
    environment: [ NO_PROMETHEUS ]
    export: ${CYBER_DOJO_RUNNER_PORT}
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
