version: 2
jobs:
  build-publish:

    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build image, test it, tag it, publish it
          command: |
            set -e
            ./build_test_tag_publish.sh

  deploy-to-beta:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud, deploy to beta with helm
          command: |
            set -e
            ./sh/deploy_to_beta.sh

  deploy-to-prod:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud, deploy to prod with helm
          command: |
            set -e
            ./sh/deploy_to_prod.sh

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-publish:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
      - deploy-to-beta:
          context: cyberdojo-context
          requires:
            - build-publish
      - approve-to-prod:
          type: approval
          requires:
            - deploy-to-beta
      - deploy-to-prod:
          context: cyberdojo-context
          requires:
            - approve-to-prod
