# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# app name
fullnameOverride: "ragger"

# deployment spec
replicaCount: 1


volumes: 
  - name: ragger-tmp-dir
    emptyDir: 
      medium: Memory
      sizeLimit: "64Mi"   


# containers
# provide default values that you HAVE to overwrite in your values.yaml file
containers: 
  - name: ragger
    image: cyberdojo/ragger
    tag: "84aef8e"
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: ragger-tmp-dir
        mountPath: /tmp
        readOnly: false 

    resources: 
      limits:
       memory: 32Mi
      requests:
       memory: 32Mi
    # livenessProbe:
    #   path: /health
    #   port: 80
    # readinessProbe:
    #   path: /health
    #   port: 80

envFromSecret: {}
 

nodeSelector: {}

affinity: {}

tolerations: []

# service
service: 
  port: 5537

  
  
